version: "3"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: ${MSSQL_PID}
    ports:
      - "${MSSQL_PORT}:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - sqlserver-network

  azure-data-studio:
    image: mcr.microsoft.com/azure-sql-edge
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "${AZURE_STUDIO_PORT}:1433"
    depends_on:
      - db
    networks:
      - sqlserver-network

networks:
  sqlserver-network:
    driver: bridge

volumes:
  sqlserver-data:
    driver: local 