version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  admin:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PHP_PG_ADMIN_SERVER_HOST: ${PHP_PG_ADMIN_SERVER_HOST}
      PHP_PG_ADMIN_SERVER_PORT: ${PHP_PG_ADMIN_SERVER_PORT}
    ports:
      - "${PGADMIN_DEFAULT_PORT}:80"
    depends_on:
      - db

volumes:
  postgres-data:
    driver: local
